[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = false
via_ir = false
debug = true  # Enable debug information
solc = "0.8.26"  # Use the version compatible with your contracts
rpc_url = "http://127.0.0.1:8545"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

